baseurl = "http://ns-rokuyon.github.io/"
languageCode = "jp"
title = "ns64's blog"
theme = "greyshade"
hasCJKLanguage = true
# pygmentscodefences = true
# pygmentsstyle = "monokai"
# PygmentsOptions = "linenos=table,nobackground=true"

[taxonomies]
category = "categories"

[params]
twitter_user = "ns_rokuyon"
github_user = "ns-rokuyon"
twitter_tweet_button = true

[author]
name = "ns64"
email = "ness3psi@gmail.com"
